spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/merpatidb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: NOVIANTO
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 20
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate.type.descriptor.sql: trace
      springframework:
        security: DEBUG
        web.cors: DEBUG

app:
  uploadto:
    cdn: ./cdn/